name: Eric's Blog
description: A place for sharing, and recording, and learning!
url: "http://rootshady.com"
#url: ""
baseurl: ""
paginate_path: "blog/page:num/"
permalink: blog/:title/

markdown: redcarpet
pygments: true
paginate: 5

categories: ['Database','Linux','LifeHacker','Java']
navigation:
 - title: Home
   url: /index.html
