name: Eric's Blog
description: A place for sharing, and recording, and learning!

url: "http://rootshady.com" 
paginate_path: "blog/page:num/"
permalink: blog/:title/

markdown: redcarpet
pygments: true
paginate: 5

navigation:
 - title: Home
   url: /index.html
